[[redirects]]
  from = "https://kea.netlify.app"
  to = "https://keajs.org"
  status = 301
  force = true

[[redirects]]
  from = "https://kea.js.org"
  to = "https://keajs.org"
  status = 301
  force = true


[[redirects]]
  from = "https://kea.js.org/*"
  to = "https://keajs.org/:splat"
  status = 301
  force = true
